# User-defined combos — add your own here.
# Each combo is a list of action names executed in order.
# Available actions: gather, gather_gem, alliance_help, barbarian_attack, scout, scout_cave_high, scout_cave_low, train_troops,
#                    villager_help, reconnect, rally_fort

combos:
  my_combo:
    - reconnect
    - alliance_help
    - gather
    - train_troops
    # - rally_fort
    # - barbarian_attack
  my_combo2:
    - reconnect
    - alliance_help
    - gather
    - train_troops
    # - rally_fort
  my_combo3:
    - reconnect
    - alliance_help
    - gather_gem
    - train_troops
    # - rally_fort
  my_combo4:
    - gather_gem
  my_combo5:
    - train_troops
