# Emulator settings
emulator_type: ldplayer
executable_path: null
instance_name: main

resolution: [1920, 1080]
dpi: 420
ram_mb: 4096
cpu_cores: 4
abi: x86_64
root_access: false
gps_location: [10.7769, 106.7009]
